FROM centos:8

# locale
RUN yum install -y langpacks-ja
ENV LANG=ja_JP.UTF-8   \
    LANGUAGE=ja_JP:ja  \
    LC_ALL=ja_JP.UTF-8 \
    TZ=Asia/Tokyo

# 環境構築
RUN yum update -y && \
    yum install -y tree vim wget openssl-devel openssh-server epel-release passwd

## rootパスワードを設定
RUN echo 'root:password' | chpasswd

# ansibleを動かすためにpythonインストール
RUN dnf install -y python3 && \
    alternatives --set python /usr/bin/python3

EXPOSE 50300
CMD /sbin/init
WORKDIR /root/
