FROM ubuntu:18.04

# locale
ENV LANG=ja_JP.UTF-8   \
    LANGUAGE=ja_JP:ja  \
    LC_ALL=ja_JP.UTF-8 \
    TZ=Asia/Tokyo

# 環境構築
RUN apt update -y && \
    apt install -y tree vim wget openssl openssh-server iproute2 sudo

## rootパスワードを設定
RUN echo 'root:password' | chpasswd

## ssh接続設定
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 50400
CMD /sbin/init
