version: '3.5' #3.4以上でなければnetworksでnameを指定不可
services:  
  web:
    image: httpd:alpine
    ports:
      - "8080:80"

  CentOS7:
    build:
      context: .
      dockerfile: "Dockerfile_centos7"
    image: centos7_i
    container_name: centos7_i
    hostname: CentOS7
    command: /sbin/init
    tty: true
    privileged: true
    ports:
      - "50121:22"
    networks:
      client_network:
        ipv4_address: 11.11.11.2

  CentOS8:
    build:
      context: .
      dockerfile: "Dockerfile_centos8"
    image: centos8_i
    container_name: centos8_i
    hostname: CentOS8
    ports:
      - "50122:22"
    tty: true
    privileged: true
    command: /sbin/init
    networks:
      client_network:

  ubuntu1804:
    build:
      context: .
      dockerfile: "Dockerfile_ubuntu1804"
    image: ubuntu1804_i
    container_name: ubuntu1804_i
    hostname: ubuntu1804
    ports:
      - "50023:22"
    tty: true
    privileged: true
    command: /sbin/init
    networks:
      client_network:

  ubuntu2004:
    build:
      context: .
      dockerfile: "Dockerfile_ubuntu2004"
    image: ubuntu2004_i
    container_name: ubuntu2004_i
    hostname: ubuntu2004
    ports:
      - "50022:22"
    tty: true
    privileged: true
    command: /sbin/init
    networks:
      client_network:

# ネットワークのサブネット値を指定する
networks:
  client_network:
    name: client_network
    ipam:
      config:
        - subnet: 11.11.11.0/24
        # docker network create --subnet=11.11.11.0/24 client_network

    # volumes:
    #   - "vol_mysql:/var/lib/mysql"
    #   - "./config_db/my.cnf:/etc/mysql/conf.d/my.cnf:ro"
      # ↓ /docker-entrypoint-initdb.dにある拡張子.sh、.sql、.sql.gzのファイルを実行する
    #   - "./config_db/start.sql:/docker-entrypoint-initdb.d/start.sql"
    # networks:
    #   - my-network

#   app:
#     build: ./config_python
#     image: im_python
#     container_name: con_py
#     env_file: ./config_db/mysql.env
#     tty: true
#     expose: 
#       - "80"
#       - "443"
#     ports:
#       - 8080:80
#       - 8081:443
#     volumes:
#       - "vol_python:/root/log"
#       - ".:/root/dirc"
#     depends_on:
#       - db 
#     networks:
#       - my-network

# volumes:
#   vol_mysql:
#   vol_python:
    
# networks:
#   my-network:
#     external: true
